### ISSUE TITLE
Bookmark file error

### ISSUE THREAD

**Issue by 0x9924** [devinsmith/w3m#3]
Hi, it seems that the bookmark file cannot be set from comand line. For example when I launch with

`./src/w3s -bookmark bookmark github.com`

and then try to add to bookmark (`ESC a`) I get the error message:

`Can't load file:///$LIB/bookmark`.

Apparently, it seems that `loadGeneralFile` is returning null because `openURL` is not setting properly of its second parameter (the `ParsedURL`). But I don't know how to debug this to get more information (tried to build with DEBUG flag and use gdb, but could't)

**Comment by devinsmith** [comment]
There appears to be a couple of problems here:
1. The bookmark libexec program isn't built by the current CMake script (that's easy enough to fix)
2. I need to dig through the code to see where $LIB gets expanded. Ideally it would get translated to something like: /usr/local/libexec/w3s/

**Comment by devinsmith** [comment]
#4 fixes the first issue, still digging into the second issue

**Comment by devinsmith** [comment]
Ok this should be fixed in latest master, the final change required installing the bookmark binary to the correct location.
Change: 067841408aeea299e1218b0a5ff4bb2944071614

You will need to actually install w3m using either `make install` or `cmake --target install` or `cmake --install` if you aren't using `make`.
